version: "3.9"

services:

    app:
        
        image: jayeshjachak/containerpulse:latest

        container_name: containerpulse-app

        restart: unless-stopped

        ports:
        - "5000:5000"

        env_file:
        - .env

        depends_on:
        - postgres

        volumes:
        # Allow the Flask container to communicate with the host Docker Engine
        - /var/run/docker.sock:/var/run/docker.sock

    postgres:

        image: postgres:16

        container_name: monitoring-db

        restart: always

        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: monitoring

        ports:
            - "5432:5432"

        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:

    postgres_data: