apiVersion: v1
kind: Service

metadata:
  name: containerpulse
  namespace: containerpulse

spec:
  type: NodePort

  selector:
    app: containerpulse

  ports:

  - port: 5000
    targetPort: 5000
    nodePort: 30080