name: ContainerPulse CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify Python
        run: |
          python --version
          pip --version

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker Image
        run: |
          docker build \
            -t containerpulse:latest \
            -t containerpulse:${{ env.IMAGE_TAG }} .

      - name: Tag Docker images
        run: |
          docker tag containerpulse:latest ${{ secrets.DOCKERHUB_USERNAME }}/containerpulse:latest
          docker tag containerpulse:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/containerpulse:${{ env.IMAGE_TAG }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/containerpulse:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/containerpulse:${{ env.IMAGE_TAG }}